# Generated by Django 3.2.15 on 2024-02-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='verse',
            name='book_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
