# Generated by Django 3.2.15 on 2024-02-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20240226_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='chapter_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_number',
            field=models.IntegerField(blank=True),
        ),
    ]
